### ISSUE TITLE
Bad proguard rules?

### ISSUE THREAD

**Issue by otormaigh** [otormaigh/lazyotp-android#40]
Getting the following when making an API call

```
E/AndroidRuntime: FATAL EXCEPTION: e.o0 Dispatcher
    Process: ie.otormaigh.lazyotp, PID: 13590
    java.lang.IncompatibleClassChangeError: The method 'e.j0 e.i0.a(java.lang.String)' was expected to be of type virtual but instead was found to be of type static (declaration of 'e.v0' appears in base.apk)
        at e.v0.D(Unknown Source:2)
        at g.j0.d(Unknown Source:16)
        at a.b.h.k0.y(Unknown Source:4)
        at e.z0.f.g.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

// Deobfuscated
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: ie.otormaigh.lazyotp, PID: 17984
    java.lang.IncompatibleClassChangeError: The method 'okhttp3.MediaType okhttp3.MediaType$Companion.get(java.lang.String)' was expected to be of type virtual but instead was found to be of type static (declaration of 'okhttp3.ResponseBody$Companion$asResponseBody$1' appears in base.apk)
        at okhttp3.ResponseBody$Companion$asResponseBody$1.contentType(Unknown Source:2)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(Unknown Source:43)
        at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:3)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(Unknown Source:15)
        at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:3)
        at okhttp3.internal.cache.CacheInterceptor.intercept(Unknown Source:27)
        at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:3)
        at okhttp3.internal.http.BridgeInterceptor.intercept(Unknown Source:14)
        at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:3)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(Unknown Source:25)
        at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:3)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(Unknown Source:10)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by otormaigh** [comment]
Setting `android.enableR8.fullMode` to false 'fixes' it, but I'd rather keep that enabled.

**Comment by otormaigh** [comment]
Looks like it was a bug introduced in the latest Android Gradle Plugin (https://issuetracker.google.com/issues/181493713).

Adding the following to `proguard-rules.pro` fixes it. 
```
-keep class okhttp3.MediaType$Companion { *; }
```
